name = "LiteQTL"
uuid = "85e3bc59-379b-574d-918d-c856ad6b8b91"
authors = ["Chelsea Trotter", "Sen Research"]
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CSV = "0.7"
CUDA = "2.3"
DataFrames = "0.21"
julia = "1.5"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "Documenter"]
